// src/styles/InventoryDetailScreen.styles.ts
import { StyleSheet, Dimensions } from 'react-native';
import { colors } from './globalStyles';
import { wp, hp, fs } from '../utils/responsive';

const { width } = Dimensions.get('window');

export const inventoryDetailStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.gray50,
  },
  scrollView: {
    flex: 1,
  },
  content: {
    paddingHorizontal: wp(4),
    paddingVertical: hp(2),
  },
  sectionCard: {
    backgroundColor: colors.white,
    borderRadius: wp(4),
    padding: wp(6),
    marginBottom: hp(2),
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
    borderWidth: 1,
    borderColor: colors.gray200,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: hp(2),
  },
  sectionIcon: {
    width: wp(10),
    height: wp(10),
    borderRadius: wp(2.5),
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: wp(3),
  },
  sectionTitle: {
    fontSize: fs(18),
    fontWeight: '700',
    color: colors.gray900,
    flex: 1,
  },
  headerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: hp(3),
  },
  companyIcon: {
    width: wp(16),
    height: wp(16),
    borderRadius: wp(4),
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: wp(4),
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  companyInfo: {
    flex: 1,
  },
  companyName: {
    fontSize: fs(20),
    fontWeight: '700',
    color: colors.gray900,
    marginBottom: hp(0.5),
  },
  companySubtitle: {
    fontSize: fs(14),
    color: colors.gray600,
  },
  formGrid: {
    marginBottom: hp(2),
  },
  formRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: hp(2),
  },
  formField: {
    width: '48%',
  },
  formFieldFull: {
    width: '100%',
    marginBottom: hp(2),
  },
  fieldLabel: {
    fontSize: fs(12),
    fontWeight: '600',
    color: colors.gray700,
    marginBottom: hp(1),
  },
  inputField: {
    borderWidth: 1,
    borderColor: colors.gray300,
    borderRadius: wp(3),
    paddingHorizontal: wp(4),
    paddingVertical: hp(1.5),
    backgroundColor: colors.gray100,
  },
  inputText: {
    fontSize: fs(14),
    color: colors.gray800,
  },
  monoText: {
    fontFamily: 'monospace',
  },
  documentInfoCard: {
    backgroundColor: colors.primary + '10',
    borderRadius: wp(3),
    padding: wp(4),
    borderWidth: 1,
    borderColor: colors.primary + '30',
  },
  documentInfoTitle: {
    fontSize: fs(14),
    fontWeight: '600',
    color: colors.primary,
    marginBottom: hp(1.5),
  },
  documentInfoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: hp(1),
  },
  documentInfoLabel: {
    fontSize: fs(12),
    color: colors.primary,
  },
  documentInfoValue: {
    fontSize: fs(12),
    fontWeight: '600',
    color: colors.primary,
  },
  statusBadge: {
    backgroundColor: colors.warning + '20',
    paddingHorizontal: wp(2),
    paddingVertical: hp(0.5),
    borderRadius: wp(2),
  },
  statusText: {
    fontSize: fs(10),
    fontWeight: '500',
    color: colors.warning,
  },
  warehouseGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  warehouseField: {
    width: '48%',
  },
  warehouseInput: {
    borderWidth: 1,
    borderColor: colors.gray300,
    borderRadius: wp(3),
    paddingHorizontal: wp(4),
    paddingVertical: hp(1.5),
    backgroundColor: colors.gray100,
  },
  warehouseDescription: {
    fontSize: fs(11),
    color: colors.gray500,
    marginTop: hp(1),
  },
  mobileCardView: {
    display: width < 768 ? 'flex' : 'none',
  },
  mobileCard: {
    backgroundColor: colors.gray50,
    padding: wp(4),
    borderRadius: wp(3),
    borderWidth: 1,
    borderColor: colors.gray200,
  },
  mobileCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: hp(2),
  },
  mobileCardLabel: {
    fontSize: fs(10),
    color: colors.gray500,
    marginBottom: hp(0.5),
  },
  mobileCardValue: {
    fontFamily: 'monospace',
    fontSize: fs(12),
    fontWeight: '600',
  },
  mobileCardAmount: {
    alignItems: 'flex-end',
  },
  mobileCardAmountText: {
    fontSize: fs(12),
    fontWeight: '700',
    color: colors.primary,
  },
  mobileCardRow: {
    marginBottom: hp(2),
  },
  mobileCardText: {
    fontSize: fs(12),
    color: colors.gray800,
  },
  mobileCardGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: hp(2),
  },
  mobileCardGridItem: {
    flex: 1,
    marginHorizontal: wp(1),
  },
  mobileCardGridValue: {
    fontSize: fs(11),
    fontWeight: '600',
  },
  desktopTableView: {
    display: width >= 768 ? 'flex' : 'none',
  },
  tableHeader: {
    flexDirection: 'row',
    borderBottomWidth: 2,
    borderBottomColor: colors.gray200,
    paddingVertical: hp(1.5),
  },
  tableHeaderCell: {
    fontSize: fs(12),
    fontWeight: '700',
    color: colors.gray700,
    textAlign: 'left',
    paddingHorizontal: wp(2),
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: colors.gray100,
    paddingVertical: hp(1.5),
    alignItems: 'center',
  },
  tableCell: {
    paddingHorizontal: wp(2),
    justifyContent: 'center',
  },
  tableInput: {
    borderWidth: 1,
    borderColor: colors.gray300,
    borderRadius: wp(2),
    paddingHorizontal: wp(2),
    paddingVertical: hp(1),
    backgroundColor: colors.gray100,
  },
  tableInputText: {
    fontSize: fs(11),
    color: colors.gray800,
  },
  centerText: {
    textAlign: 'center',
    fontWeight: '600',
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  checkbox: {
    width: wp(4),
    height: wp(4),
    borderRadius: wp(1),
    backgroundColor: colors.primary,
    borderWidth: 1,
    borderColor: colors.gray300,
  },
  checkboxLabel: {
    fontSize: fs(11),
    color: colors.gray700,
    marginLeft: wp(2),
  },
  totalAmount: {
    fontSize: fs(14),
    fontWeight: '700',
    color: colors.primary,
  },
  summaryGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  summaryCard: {
    flex: 1,
    borderRadius: wp(3),
    padding: wp(4),
    marginHorizontal: wp(1),
    borderWidth: 2,
  },
  summaryCardIncoming: {
    backgroundColor: colors.success + '10',
    borderColor: colors.success + '30',
  },
  summaryCardOutgoing: {
    backgroundColor: colors.error + '10',
    borderColor: colors.error + '30',
  },
  summaryCardDifference: {
    backgroundColor: colors.primary + '10',
    borderColor: colors.primary + '30',
  },
  summaryHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: hp(1),
  },
  summaryTitleIncoming: {
    fontSize: fs(10),
    fontWeight: '600',
    color: colors.success,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  summaryTitleOutgoing: {
    fontSize: fs(10),
    fontWeight: '600',
    color: colors.error,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  summaryTitleDifference: {
    fontSize: fs(10),
    fontWeight: '600',
    color: colors.primary,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  summaryAmountIncoming: {
    fontSize: fs(20),
    fontWeight: '700',
    color: colors.success,
    marginTop: hp(0.5),
  },
  summaryAmountOutgoing: {
    fontSize: fs(20),
    fontWeight: '700',
    color: colors.error,
    marginTop: hp(0.5),
  },
  summaryAmountDifference: {
    fontSize: fs(20),
    fontWeight: '700',
    color: colors.primary,
    marginTop: hp(0.5),
  },
  summaryCurrencyIncoming: {
    fontSize: fs(10),
    fontWeight: '500',
    color: colors.success,
  },
  summaryCurrencyOutgoing: {
    fontSize: fs(10),
    fontWeight: '500',
    color: colors.error,
  },
  summaryCurrencyDifference: {
    fontSize: fs(10),
    fontWeight: '500',
    color: colors.primary,
  },
  summaryIconIncoming: {
    width: wp(12),
    height: wp(12),
    borderRadius: wp(6),
    backgroundColor: colors.success + '20',
    alignItems: 'center',
    justifyContent: 'center',
  },
  summaryIconOutgoing: {
    width: wp(12),
    height: wp(12),
    borderRadius: wp(6),
    backgroundColor: colors.error + '20',
    alignItems: 'center',
    justifyContent: 'center',
  },
  summaryIconDifference: {
    width: wp(12),
    height: wp(12),
    borderRadius: wp(6),
    backgroundColor: colors.primary + '20',
    alignItems: 'center',
    justifyContent: 'center',
  },
  summaryBadgeIncoming: {
    backgroundColor: colors.success + '20',
    paddingHorizontal: wp(2),
    paddingVertical: hp(0.5),
    borderRadius: wp(2),
    marginTop: hp(1),
  },
  summaryBadgeOutgoing: {
    backgroundColor: colors.error + '20',
    paddingHorizontal: wp(2),
    paddingVertical: hp(0.5),
    borderRadius: wp(2),
    marginTop: hp(1),
  },
  summaryBadgeDifference: {
    backgroundColor: colors.primary + '20',
    paddingHorizontal: wp(2),
    paddingVertical: hp(0.5),
    borderRadius: wp(2),
    marginTop: hp(1),
  },
  summaryBadgeTextIncoming: {
    fontSize: fs(9),
    fontWeight: '500',
    color: colors.success,
  },
  summaryBadgeTextOutgoing: {
    fontSize: fs(9),
    fontWeight: '500',
    color: colors.error,
  },
  summaryBadgeTextDifference: {
    fontSize: fs(9),
    fontWeight: '500',
    color: colors.primary,
  },
  commentsInput: {
    borderWidth: 1,
    borderColor: colors.gray300,
    borderRadius: wp(3),
    paddingHorizontal: wp(4),
    paddingVertical: hp(1.5),
    backgroundColor: colors.gray100,
    minHeight: hp(8),
  },
  commentsText: {
    fontSize: fs(14),
    color: colors.gray800,
  },
  activityLog: {
    marginTop: hp(1),
  },
  activityItem: {
    backgroundColor: colors.gray50,
    borderRadius: wp(3),
    paddingLeft: wp(6),
    paddingVertical: hp(1.5),
    borderLeftWidth: 4,
    borderLeftColor: colors.primary,
    marginBottom: hp(1),
  },
  activityContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  activityInfo: {
    flex: 1,
  },
  activityAction: {
    fontSize: fs(14),
    fontWeight: '600',
    color: colors.gray900,
    marginBottom: hp(0.5),
  },
  activityDetails: {
    fontSize: fs(11),
    color: colors.gray600,
    marginBottom: hp(0.5),
  },
  activityUser: {
    fontWeight: '500',
  },
  activityTime: {
    fontWeight: '500',
  },
  activityType: {
    backgroundColor: colors.primary + '20',
    paddingHorizontal: wp(3),
    paddingVertical: hp(0.5),
    borderRadius: wp(2),
  },
  activityTypeText: {
    fontSize: fs(9),
    fontWeight: '500',
    color: colors.primary,
  },
  actionButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: wp(3),
  },
  actionButton: {
    borderRadius: wp(3),
    paddingHorizontal: wp(6),
    paddingVertical: hp(1.5),
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  actionButtonPrimary: {
    backgroundColor: colors.primary,
  },
  actionButtonSuccess: {
    backgroundColor: colors.success,
  },
  actionButtonText: {
    fontSize: fs(14),
    fontWeight: '600',
    marginLeft: wp(2),
  },
  actionButtonTextPrimary: {
    color: colors.white,
  },
  actionButtonTextSuccess: {
    color: colors.white,
  },
  // Mobile-specific styles
  mobileHeaderContainer: {
    alignItems: 'center',
    marginBottom: hp(3),
  },
  mobileTitle: {
    fontSize: fs(20),
    fontWeight: '700',
    color: colors.gray900,
    marginBottom: hp(1),
  },
  mobileSubtitle: {
    fontSize: fs(14),
    color: colors.gray600,
  },
  mobileFormGrid: {
    gap: hp(2),
  },
  mobileFormRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: hp(1),
    borderBottomWidth: 1,
    borderBottomColor: colors.gray100,
  },
  mobileFieldLabel: {
    fontSize: fs(14),
    fontWeight: '600',
    color: colors.gray700,
    flex: 1,
  },
  mobileFieldValue: {
    fontSize: fs(14),
    color: colors.gray900,
    flex: 1,
    textAlign: 'right',
  },
  mobileWarehouseGrid: {
    gap: hp(2),
  },
  mobileWarehouseCard: {
    backgroundColor: colors.gray50,
    padding: wp(4),
    borderRadius: wp(3),
    borderWidth: 1,
    borderColor: colors.gray200,
  },
  mobileWarehouseLabel: {
    fontSize: fs(12),
    fontWeight: '600',
    color: colors.gray600,
    marginBottom: hp(0.5),
  },
  mobileWarehouseValue: {
    fontSize: fs(14),
    fontWeight: '600',
    color: colors.gray900,
  },
  mobileItemCard: {
    backgroundColor: colors.gray50,
    padding: wp(4),
    borderRadius: wp(3),
    marginBottom: hp(2),
    borderWidth: 1,
    borderColor: colors.gray200,
  },
  mobileItemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: hp(2),
  },
  mobileItemCode: {
    fontSize: fs(12),
    fontWeight: '600',
    color: colors.primary,
    fontFamily: 'monospace',
  },
  mobileItemAmount: {
    fontSize: fs(14),
    fontWeight: '700',
    color: colors.success,
  },
  mobileItemName: {
    fontSize: fs(14),
    fontWeight: '600',
    color: colors.gray900,
    marginBottom: hp(2),
  },
  mobileItemGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: hp(1),
  },
  mobileItemGridItem: {
    flex: 1,
    alignItems: 'center',
  },
  mobileItemLabel: {
    fontSize: fs(10),
    color: colors.gray600,
    marginBottom: hp(0.5),
  },
  mobileItemValue: {
    fontSize: fs(12),
    fontWeight: '600',
    color: colors.gray900,
  },
  mobileItemDescription: {
    fontSize: fs(12),
    color: colors.gray600,
    fontStyle: 'italic',
    marginTop: hp(1),
  },
  noItemsText: {
    fontSize: fs(14),
    color: colors.gray500,
    textAlign: 'center',
    paddingVertical: hp(4),
  },
  mobileSummaryGrid: {
    gap: hp(2),
  },
  mobileSummaryCard: {
    backgroundColor: colors.gray50,
    padding: wp(4),
    borderRadius: wp(3),
    borderWidth: 1,
    borderColor: colors.gray200,
    alignItems: 'center',
  },
  mobileSummaryLabel: {
    fontSize: fs(12),
    fontWeight: '600',
    color: colors.gray600,
    marginBottom: hp(1),
  },
  mobileSummaryValue: {
    fontSize: fs(16),
    fontWeight: '700',
    color: colors.gray900,
  },
  mobileCommentsContainer: {
    backgroundColor: colors.gray50,
    padding: wp(4),
    borderRadius: wp(3),
    borderWidth: 1,
    borderColor: colors.gray200,
  },
  mobileCommentsText: {
    fontSize: fs(14),
    color: colors.gray800,
    lineHeight: fs(20),
  },
  mobileInfoGrid: {
    gap: hp(1.5),
  },
  mobileInfoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: hp(1),
  },
  mobileInfoLabel: {
    fontSize: fs(14),
    fontWeight: '600',
    color: colors.gray700,
  },
  mobileInfoValue: {
    fontSize: fs(14),
    color: colors.gray900,
  },
  mobileActionButtonsContainer: {
    flexDirection: 'row',
    gap: wp(3),
  },
  mobileActionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: hp(1.5),
    paddingHorizontal: wp(4),
    borderRadius: wp(3),
    gap: wp(2),
  },
  mobileActionButtonPrimary: {
    backgroundColor: colors.primary,
  },
  mobileActionButtonSuccess: {
    backgroundColor: colors.success,
  },
  mobileActionButtonText: {
    fontSize: fs(14),
    fontWeight: '600',
    color: colors.white,
  },
  // Activity Log Styles
  mobileActivityLog: {
    gap: hp(2),
  },
  mobileActivityItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingVertical: hp(1.5),
    borderLeftWidth: 3,
    borderLeftColor: colors.primary,
    paddingLeft: wp(4),
    backgroundColor: colors.gray50,
    borderRadius: wp(2),
    marginBottom: hp(1),
  },
  mobileActivityIcon: {
    width: wp(8),
    height: wp(8),
    borderRadius: wp(4),
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: wp(3),
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  mobileActivityContent: {
    flex: 1,
  },
  mobileActivityTitle: {
    fontSize: fs(14),
    fontWeight: '600',
    color: colors.gray900,
    marginBottom: hp(0.5),
  },
  mobileActivityDetails: {
    fontSize: fs(12),
    color: colors.gray600,
    marginBottom: hp(0.5),
  },
  mobileActivityUser: {
    fontWeight: '600',
    color: colors.primary,
  },
  mobileActivityTime: {
    fontSize: fs(11),
    color: colors.gray500,
    fontStyle: 'italic',
  },
  mobileActivityBadge: {
    backgroundColor: colors.primary + '20',
    paddingHorizontal: wp(2),
    paddingVertical: hp(0.5),
    borderRadius: wp(2),
    alignSelf: 'flex-start',
  },
  mobileActivityBadgeText: {
    fontSize: fs(10),
    fontWeight: '600',
    color: colors.primary,
  },
  // Items Summary Styles
  sectionHeaderWithTotal: {
    flexDirection: 'row',
    justifyContent: 'space_between',
    alignItems: 'center',
    marginBottom: hp(2),
  },
  totalItemsContainer: {
    backgroundColor: colors.primary + '20',
    paddingHorizontal: wp(3),
    paddingVertical: hp(0.5),
    borderRadius: wp(2),
  },
  totalItemsText: {
    fontSize: fs(12),
    fontWeight: '600',
    color: colors.primary,
  },
  // Enhanced Item Card Styles
  enhancedItemCard: {
    backgroundColor: colors.white,
    borderRadius: wp(3),
    padding: wp(4),
    marginBottom: hp(2),
    borderWidth: 1,
    borderColor: colors.gray200,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  enhancedItemHeader: {
    marginBottom: hp(1.5),
  },
  itemCodeContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  enhancedItemCode: {
    fontSize: fs(12),
    fontWeight: '700',
    color: colors.primary,
    fontFamily: 'monospace',
    backgroundColor: colors.primary + '10',
    paddingHorizontal: wp(2),
    paddingVertical: hp(0.5),
    borderRadius: wp(1.5),
  },
  statusIndicator: {
    paddingHorizontal: wp(2.5),
    paddingVertical: hp(0.5),
    borderRadius: wp(2),
  },
  enhancedStatusText: {
    fontSize: fs(10),
    fontWeight: '600',
  },
  enhancedItemName: {
    fontSize: fs(14),
    fontWeight: '600',
    color: colors.gray900,
    marginBottom: hp(1.5),
    lineHeight: fs(18),
  },
  quantityContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: colors.gray50,
    padding: wp(3),
    borderRadius: wp(2),
  },
  quantityInfo: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  quantityLabel: {
    fontSize: fs(12),
    color: colors.gray600,
    marginRight: wp(2),
  },
  quantityValue: {
    fontSize: fs(16),
    fontWeight: '700',
    color: colors.primary,
  },
  uomContainer: {
    backgroundColor: colors.white,
    paddingHorizontal: wp(2.5),
    paddingVertical: hp(0.5),
    borderRadius: wp(1.5),
    borderWidth: 1,
    borderColor: colors.gray300,
  },
  uomText: {
    fontSize: fs(11),
    fontWeight: '600',
    color: colors.gray700,
  },
  itemDescription: {
    fontSize: fs(12),
    color: colors.gray600,
    fontStyle: 'italic',
    marginTop: hp(1),
  },
  // Empty State Styles
  emptyStateContainer: {
    alignItems: 'center',
    paddingVertical: hp(6),
    paddingHorizontal: wp(4),
  },
  emptyStateIcon: {
    fontSize: fs(48),
    marginBottom: hp(2),
  },
  emptyStateText: {
    fontSize: fs(16),
    fontWeight: '600',
    color: colors.gray700,
    marginBottom: hp(0.5),
  },
  emptyStateSubtext: {
    fontSize: fs(14),
    color: colors.gray500,
  },
  // Comment Form Styles
  currentCommentContainer: {
    backgroundColor: colors.gray50,
    padding: wp(4),
    borderRadius: wp(2),
    marginBottom: hp(2),
    borderLeftWidth: 3,
    borderLeftColor: colors.primary,
  },
  currentCommentLabel: {
    fontSize: fs(12),
    fontWeight: '600',
    color: colors.gray600,
    marginBottom: hp(0.5),
  },
  currentCommentText: {
    fontSize: fs(14),
    color: colors.gray800,
    lineHeight: fs(18),
  },
  commentFormContainer: {
    marginTop: hp(1),
  },
  commentInput: {
    borderWidth: 1,
    borderColor: colors.gray300,
    borderRadius: wp(3),
    paddingHorizontal: wp(4),
    paddingVertical: hp(2),
    backgroundColor: colors.white,
    fontSize: fs(14),
    color: colors.gray800,
    textAlignVertical: 'top',
    marginBottom: hp(2),
    width: '100%',
  },
  submitButton: {
    backgroundColor: colors.primary,
    paddingVertical: hp(1.5),
    paddingHorizontal: wp(6),
    borderRadius: wp(2.5),
    alignItems: 'center',
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  submitButtonDisabled: {
    backgroundColor: colors.gray300,
    shadowOpacity: 0,
    elevation: 0,
  },
  submitButtonText: {
    fontSize: fs(14),
    fontWeight: '600',
    color: colors.white,
  },
  submitButtonTextDisabled: {
    color: colors.gray500,
  },
});


