// src/utils/error/homeScreen.codes.ts
export enum HomeScreenErrorCode {
  // Data Loading Errors
  CHECKIN_DATA_LOAD_FAILED = 'HOME_CHECKIN_DATA_LOAD_FAILED',
  
  // Location Service Errors
  GPS_SERVICE_DISABLED = 'HOME_GPS_SERVICE_DISABLED',
  LOCATION_SERVICE_CHECK_FAILED = 'HOME_LOCATION_SERVICE_CHECK_FAILED',
  
  // Location Permission Errors
  LOCATION_PERMISSION_DENIED = 'HOME_LOCATION_PERMISSION_DENIED',
  
  // Location Timeout Errors (Multi-level strategy)
  LOCATION_TIMEOUT_HIGH_ACCURACY = 'HOME_LOCATION_TIMEOUT_HIGH',
  LOCATION_TIMEOUT_BALANCED_ACCURACY = 'HOME_LOCATION_TIMEOUT_BALANCED', 
  LOCATION_TIMEOUT_LOW_ACCURACY = 'HOME_LOCATION_TIMEOUT_LOW',
  
  // Location Data Errors
  LOCATION_COORDS_INVALID = 'HOME_LOCATION_COORDS_INVALID',
  LOCATION_NETWORK_ERROR = 'HOME_LOCATION_NETWORK_ERROR',
  LOCATION_GENERAL_ERROR = 'HOME_LOCATION_GENERAL_ERROR',
  
  // Checkin Validation Errors
  CHECKIN_NO_VALID_GPS = 'HOME_CHECKIN_NO_VALID_GPS',
  CHECKIN_NO_LOCATION_DATA = 'HOME_CHECKIN_NO_LOCATION_DATA',
  
  // Checkin API Errors
  CHECKIN_API_SUBMIT_FAILED = 'HOME_CHECKIN_API_SUBMIT_FAILED',
  CHECKIN_UNKNOWN_ERROR = 'HOME_CHECKIN_UNKNOWN_ERROR',
  
  // System Initialization Errors
  INITIALIZATION_FAILED = 'HOME_INITIALIZATION_FAILED'
}